services:
  - type: web
    name: hugo-quickstart
    env: static
    root: website
    buildCommand: hugo --gc --minify
    preDeployCommand: git submodule update --init --recursive
    staticPublishPath: public
